// This file is GENERATED by buildPlugin.mjs script
import {PluginEnv} from "lib/plugin/PluginEnv"
export const PLUGIN_ENV = new PluginEnv({
    env: "prod",
    pluginName: "GrandMA3 Autozoom Plugin",
    pluginId: "naostage__grandma3-autozoom-plugin__v0_1_0",
    pluginVersion: "0.1.0",
    author: "Anatole Rochut"
})
